### ISSUE TITLE
Genome version for hordeum vulgare

### ISSUE THREAD

**Issue by sebel76** [dvitsios/mirnovo#1]
Dear,

I work on barley and I am motivated to use your pipeline. I download the genome as recommended. When I check the hvu.chrom.sizes file, that look like the genome v1.

Can you inform me which are available?

While an important improve of the genome was release, Is it possible to install the genome version 2 on your program?

The version could be available on the ftp site of ensembl plant server release 37.

Thanks you to help me!

Sébastien

**Comment by dvitsios** [comment]
Hi Sebastien,

the **hvu** genome that is currently installed on the web-server is indeed v1.
However, you can download and build any genome you want when using the standalone version of **mirnovo**.  Instructions for doing so are available here:
[http://wwwdev.ebi.ac.uk/enright-dev/mirnovo-standalone-pkg/Genome-Annotation-1.0/README](http://wwwdev.ebi.ac.uk/enright-dev/mirnovo-standalone-pkg/Genome-Annotation-1.0/README)

--> `* Install a Reference Genome manually (e.g. Homo sapiens - hsa) * section.`

Based on these instructions, in order to install the hvu v2 genome in your standalone version of **mirnovo** you need to run the following commands:

```
cd [_PATH_to_YOUR_mirnovo-standalone-pkg_]/Genome-Annotation-1.0
mkdir hvu
cd hvu
wget ftp://ftp.ensemblgenomes.org/pub/plants/release-37/fasta/hordeum_vulgare/dna/Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna_rm.toplevel.fa.gz
gunzip Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna_rm.toplevel.fa.gz
bowtie2-build Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna_rm.toplevel.fa hvu
../tools/faToTwoBit Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna_rm.toplevel.fa hvu.2bit
../tools/twoBitInfo hvu.2bit stdout | sort -k2rn > hvu.chrom.sizes
```

Updated versions for some genomes (including hvu) may also be added to the web-server later in the year.

Hope that helps!
Dimitris
